version: '2.1'

services:
  redis:
    image: tempworks/redis-server
    container_name: redis-server
    expose:
      - "6379"
    ports:
      - "6379:6379" # REMARK: This is currently required, needs investigation

  auth:
    image: tempworks/auth-service
    container_name: twas
    environment:
      ASPNETCORE_APPSETTINGS_FILEPATH: config\twas-appsettings.json
    volumes:
      - c:/shared-vol/config:c:/app/config
      - c:/shared-vol/logs:c:/app/logs
    expose:
      - "80"
    ports:
      - "88:80"
    depends_on:
      - redis

  srps:
    image: tempworks/sovren-srps
    container_name: sovren-srps
    expose:
      - "80"
    ports:
      - "55100:80" # REMARK: This is currently required, needs investigation

  convert:
    image: tempworks/convert-service
    container_name: convert-service
    expose:
      - "80"
    ports:
      - "55200:80" # REMARK: This is currently required, needs investigation

  api:
    image: tempworks/api-v3
    container_name: twapi
    environment:
      ASPNETCORE_APPSETTINGS_FILEPATH: config\twapi-appsettings.json
    volumes:
      - c:/shared-vol/config:c:/app/config
      - c:/shared-vol/logs:c:/app/logs
    expose:
      - "80"
    ports:
      - "80:80"
    depends_on:
      - auth
      - redis
      - srps
      - convert

networks:
  default:
    external:
      name: nat
